---
title: "Supplement 1"
subtitle: "Descriptive statistics for the whole cohort"
author: "Peter Kamerman and Prinisha Pillay"
date: "`r format(Sys.Date(), '%d %B %Y')`"
---

```{r setup, include = FALSE}
# Load packages
library(magrittr)
library(tidyverse)
library(rcompanion)
library(boot)
library(skimr)

# Set plot theme
theme_set(new = theme_bw(base_size = 14))

# knitr options
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE, 
                      fig.width = 5,
                      fig.height = 6,
                      fig.align = 'center',
                      fig.path = 'figures/suppl-01-descriptive-whole-cohort/')
```

----

This script generates descriptive statistics for variables collected at baseline (visit day: 0, visit_number: 1) for the whole cohort, irrespective of whether they went on to develop sensory neuropathy (SN) or not.

The following data columns were not analysed:

- `pain` and `pain score`: related to SN only, therefore not relevant at baseline when everyone was free from SN.  

- `*_record`: inconsistent patient records.  

- `hba1c_percent` and `vitaminB12_pmol.l`: These data were only used to classify individuals as having diabetes or vitamin B12 deficiency when cleaning the data _(see:clean-data.R)_.  

- `ID`, `visit_number`, `visit_day`, `hivsn_present`, `visit_months`: provide sorting and grouping information only. 

----

# Import data
```{r import}
data <- read_rds('data-cleaned/clean_data.rds') %>% 
    # Filter for visit one
    filter(visit_number == 1) %>% 
    # Remove columns that won't be analysed
    select(-starts_with('pain'), -ends_with('_record'), 
           -visit_number, -visit_months, 
           -hba1c_percent, -vitaminB12_pmol.l) 
```

# Inspect data
```{r quick_look}
# Dimensions 
dim(data) 
# Column names
names(data)
# Head and tail
head(data)
tail(data)
# Data structure
glimpse(data)
```

----

# Analyses

## Age
```{r age}
# Tabular summary
data %>% 
    select(age_years) %>% 
    skim()

# 95% bootstrap confidence interval of the mean age
## Method = BCa, Resamples = 1999
set.seed(1234)
groupwiseMean(age_years ~ 1, 
              data = data, 
              R = 1999, 
              traditional = FALSE, 
              boot = TRUE, 
              bca = TRUE)[c(2:3, 5, 6, 7)]

# Plot
data %>%
    ggplot(data = .) +
    aes(y = age_years, 
        x = 'All patients') +
    geom_boxplot() +
    geom_jitter(height = 0) +
    labs(title = 'Age at recruitment',
         y = 'Age (years)',
         x = 'All participants') +
    theme(axis.text.x = element_blank())
```

## Body mass
```{r mass}
# Tabular summary
data %>%
    select(mass_kg) %>% 
    skim()

# 95% bootstrap confidence interval of thew mean age
## Method = BCa, Resamples = 1999
set.seed(1234)
groupwiseMean(mass_kg ~ 1, 
              data = data, 
              R = 1999, 
              traditional = FALSE, 
              boot = TRUE, 
              bca = TRUE)[c(2:3, 5, 6, 7)]

# Plot
data %>%
    ggplot(data = .) +
    aes(y = mass_kg, 
        x = 'All patients') +
    geom_boxplot() +
    geom_jitter(height = 0) +
    labs(title = 'Body mass at recruitment',
         y = 'Body mass (kg)') +
    theme(axis.text.x = element_blank())
```

## Height
Expect height to show sex difference, so analyse separately for males and females.
```{r height}
# Tabular summary
data %>%
    group_by(sex) %>% 
    select(height_m, sex) %>% 
    skim()

# 95% bootstrap confidence interval of the mean height
## Method = BCa, Resamples = 1999
set.seed(1234)
groupwiseMean(age_years ~ sex, 
              data = data, 
              R = 1999, 
              traditional = FALSE, 
              boot = TRUE, 
              bca = TRUE)[c(1:3, 5, 6, 7)]

# Plots 
data %>%
    ggplot(data = .) +
    aes(y = height_m, 
        x = sex) +
    geom_boxplot() +
    geom_jitter(height = 0) +
    labs(title = 'Height at recruitment, grouped by sex',
         y = 'Height (m)',
         x = 'Sex')
```

## Sex
```{r sex}
# Tabular summary
data %>%
    select(sex) %>% 
    skim()

# 95% bootstrap confidence interval of the proportion of females
## Method = BCa, Resamples = 1999
set.seed(1234)
boot.ci(boot(data = data, 
             statistic = function(d, i){mean(d[i, 'sex'] == 'F')}, 
             R = 1999, 
             stype = 'i'), 
        type = 'bca') %>% 
    data_frame(n = nrow(filter(data, !is.na(sex))), 
      Proportion = round(.$t0, 3), 
      Conf.level = 0.95, 
      Bca.lower = round(.$bca[[4]], 3),
      Bca.upper = round(.$bca[[5]], 3)) %>%
    .[1, -1] %>% 
    as.data.frame()
    
# Plot
data %>%
    ggplot(data = .) +
    aes(x = 'All participants',
        fill = sex) +
    geom_bar(position = 'fill') + 
    geom_hline(yintercept = 0.5,
               linetype = 2) +
    labs(title = 'Sex ratio at recruitment',
         subtitle = '(All participants)',
         y = 'Proportion') +
    scale_fill_grey(name = 'Sex') +
    theme(axis.text.x = element_blank())
```

## CD4 T-cell count
```{r cd4}
# Tabular summary
data %>%
    select(CD4_cell.ul) %>%  
    skim()

# 95% bootstrap confidence interval of the median CD4 T-cell count
## Method = BCa, Resamples = 1999
set.seed(1234)
groupwiseMedian(CD4_cell.ul ~ 1, 
                data = data, 
                R = 1999,
                boot = TRUE, 
                bca = TRUE)[c(2:3, 5, 6, 7)]
# Plot
data %>%
    ggplot(data = .) +
    aes(y = CD4_cell.ul, 
        x = 'All patients') +
    geom_boxplot() +
    geom_jitter(height = 0) +
    labs(title = 'CD4 T-cell count at recruitment',
         y = expression(paste('CD4 T-cell count (cells.', mu, l^-1, ')'))) +
    theme(axis.text.x = element_blank())
```

## Viral load
```{r viral_load}
# Tabular summary
data %>%
    select(viral_load_copies.ml) %>%  
    skim()

# 95% bootstrap confidence interval of the median viral load
## Method = BCa, Resamples = 1999
set.seed(1234)
groupwiseMedian(viral_load_copies.ml ~ 1, 
                data = data[!is.na(data$viral_load_copies.ml), ], # Remove <NA>
                R = 1999,
                boot = TRUE, 
                bca = TRUE)[c(2:3, 5, 6, 7)]

# Plot
data %>%
    filter(!is.na(viral_load_copies.ml)) %>%
    ggplot(data = .) +
    aes(y = viral_load_copies.ml, 
        x = 'All patients') +
    geom_boxplot() +
    geom_jitter(height = 0) +
    labs(title = 'Viral load at recruitment',
         y = expression(paste('log' [10], ' viral load (copies.ml' ^-1, ')')))  +
    theme(axis.text.x = element_blank())
```

## Alcohol
```{r alcohol}
# Tabular summary
data %>%
    select(alcohol_units.week) %>%
    mutate(drinks_alcohol = case_when(
        alcohol_units.week >= 1 ~ 'Yes',
        alcohol_units.week == 0 ~ 'No'
    )) %>% 
    mutate(drinks_alcohol = factor(drinks_alcohol)) %>% 
    group_by(drinks_alcohol) %>% 
    skim()

# 95% bootstrap confidence interval of the median alcohol consumption
## Method = BCa, Resamples = 1999
set.seed(1234)
groupwiseMedian(alcohol_units.week ~ 1, 
                data = data[data$alcohol_units.week > 0, ], # Remove none drinkers
                R = 1999, 
                boot = TRUE, 
                bca = TRUE)[c(2:3, 5, 6, 7)]

# Plot
data %>%
    filter(alcohol_units.week > 0) %>% 
    ggplot(data = .) +
    aes(x = 'Participants who drink\n(n=16)',
        y = alcohol_units.week) +
    geom_boxplot() +
    geom_jitter(height = 0) +
    labs(title = 'Alcohol consumption at recruitment',
         y = expression(paste('Alcohol consumption (units.week' ^-1, ')'))) +
    theme(axis.text.x = element_blank())
```

## TB
_Note: Treatment policy was to start some patients, irrespective of TB diagnosis, on TB treatment. Therefore current TB infection and treatment for TB analysed separately._

### Currently infected with TB
```{r tb_current}
# Tabular summary
data %>%
    select(TB_current) %>%  
    skim()

# 95% bootstrap confidence interval of the proportion with TB
## Method = BCa, Resamples = 1999
set.seed(1234)
boot.ci(boot(data = data, 
             statistic = function(d, i){mean(d[i, 'TB_current'] == 'yes')}, 
             R = 1999, 
             stype = 'i'), 
        type = 'bca') %>% 
    data_frame(n = nrow(filter(data, !is.na(TB_current))),
      Proportion = round(.$t0, 3), 
      Conf.level = 0.95, 
      Bca.lower = round(.$bca[[4]], 3),
      Bca.upper = round(.$bca[[5]], 3)) %>%
    .[1, -1] %>% 
    as.data.frame()

# Plot
data %>%
    mutate(TB_current = str_to_title(TB_current)) %>% 
    ggplot(data = .) +
    aes(x = 'All participants',
        fill = TB_current) +
    geom_bar(position = 'fill') + 
    geom_hline(yintercept = 0.5,
               linetype = 2) +
    labs(title = 'Current TB at recruitment',
         y = 'Proportion') +
    scale_fill_grey(name = 'Infected') +
    theme(axis.text.x = element_blank())
```

### Currently receiving TB treatment?
Treatment consisted of rifafour and pyridoxine (prophylaxis). Therefore only need to analyse rifafour data. Data coded as _'No'_ (not being treated), _'Yes'_ (being treated for active TB), and _'Prophylaxis'_ (being treated prophylactically for TB).
```{r tb_rifafour}
# Double-check matching between rifafour and pyridoxine columns 
unique(data$rifafour_treatment == data$pyridoxine_prophylaxis)

# Tabular summary
data %>%
    group_by(pyridoxine_prophylaxis) %>% 
    select(rifafour_treatment, pyridoxine_prophylaxis) %>%  
    skim()

# Proportion on prophylaxis treatment
## Too low to analyse separately
round(mean(data$rifafour_treatment == 'prophylaxis'), 3)

## ...so collapse 'yes' and 'prophylaxis'
data_tb <- data %>% 
    mutate(rifafour_treatment = fct_collapse(rifafour_treatment,
                                             yes = c('yes', 'prophylaxis')))

# 95% bootstrap confidence interval of the proportion on TB treatment
## Method = BCa, Resamples = 1999
set.seed(1234)
boot.ci(boot(data = data_tb, 
             statistic = function(d, i){mean(d[i, 'rifafour_treatment'] == 'yes')}, 
             R = 1999, 
             stype = 'i'), 
        type = 'bca') %>% 
    data_frame(n = nrow(filter(data_tb, !is.na(rifafour_treatment))), 
      Proportion = round(.$t0, 3), 
      Conf.level = 0.95, 
      Bca.lower = round(.$bca[[4]], 3),
      Bca.upper = round(.$bca[[5]], 3)) %>%
    .[1, -1] %>% 
    as.data.frame()

# Plot
data %>%
    mutate(rifafour_treatment = str_to_title(rifafour_treatment),
           rifafour_treatment = factor(rifafour_treatment,
                                       levels = c('No', 'Yes',
                                                  'Prophylaxis'),
                                       ordered = TRUE)) %>% 
    ggplot(data = .) +
    aes(x = 'All participants',
        fill = rifafour_treatment) +
    geom_bar(position = 'fill') + 
    geom_hline(yintercept = 0.5,
               linetype = 2) +
    labs(title = 'Being treated for TB at recruitment',
         y = 'Proportion') +
    scale_fill_grey(name = 'Treatment') +
    theme(axis.text.x = element_blank())
```

## Diabetes
Classified as diabetic based on `data$hba1c_percent` > 7%. No participants were diabetic.
```{r diabetes}
# Tabular summary
data %>%
    select(diabetic_hba1c) %>%  
    skim()
```

## Vitamin B12 deficiency
Classed as B12 deficient based on `data$vitaminB12_pmol.l` < 141 pmol/l. Only one participant had a deficiency.
```{r vitaminB12}
# Tabular summary
data %>%
    select(vitaminB12_deficiency) %>%  
    skim()
```

----

# Session information
```{r session_info}
sessionInfo()
```
